---
sidebar: sidebar 
permalink: release-notes/cache-limitations.html 
keywords: volume caching, bluexp 
summary: Les limitations connues identifient les plates-formes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du service ou qui ne fonctionnent pas correctement avec celui-ci. 
---
= Limites connues
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les limitations connues identifient les plates-formes, les périphériques ou les fonctions qui ne sont pas pris en charge par cette version du service ou qui ne fonctionnent pas correctement avec celui-ci.



== Limitation de la copie des règles d'export du cache

Les règles d'export-policy du cache ne sont pas copiées sur le volume du cache dans les situations suivantes :

* Lorsque l'environnement de travail du volume source est Amazon FSX pour NetApp ONTAP ou Cloud Volumes ONTAP et que le volume du cache est ONTAP 9.10.1 ou version antérieure.
* Lorsque l'environnement de travail du volume source est une version de ONTAP et que le volume de cache est ONTAP 9.10.1 ou une version antérieure.


Solution de contournement : vous devez créer manuellement les règles pour le volume de cache.



== La création du cache échoue pour les machines virtuelles de stockage portant le même nom

Si les clusters source et cible utilisent des machines virtuelles de stockage portant le même nom, le cache n'est pas créé.

Solution de contournement : utilisez des noms différents pour les machines virtuelles de stockage source et de destination.



== Délai d'affichage des règles d'export nouvelles ou récemment modifiées

Lors de la création d'un cache, il se peut que vous ne puissiez pas voir dans la liste une règle d'export récemment créée ou modifiée.

Solution : réessayez dans quelques minutes.



== La création du cache échoue lorsque seul le protocole CIFS est activé pour la destination

La création du cache échoue si le cluster source ou de destination possède ONTAP 9.10.1 ou une version antérieure et si seul le protocole CIFS est activé sur le cluster de destination.

Solution de contournement : utilisez un cluster de destination exécutant ONTAP 9.11.1 ou une version ultérieure, ou avec les protocoles CIFS et NFS configurés.
